### ISSUE TITLE
'Devil's Island' text doesn't display

### ISSUE THREAD

**Issue by ribbons** [mattgodbolt/jsbeeb#109]
Text based adventure game '[Devils Island](http://8bs.nerdoftheherd.com/8BS12/content/0-b-devils/)' from issue 12 of 8-Bit Software isn't displaying properly:

![jsbeeb](https://cloud.githubusercontent.com/assets/961548/13381311/cc8052ea-de50-11e5-8fb7-e4df272e8780.png)

I'm pretty sure that there is supposed to be text displaying in the blank space under the 'house' graphic, and this kinda displays when run in Master mode, but the graphics is all messed up (so I'm guessing it might not be designed for Master):

![jsbeeb_master](https://cloud.githubusercontent.com/assets/961548/13381321/07e8126e-de51-11e5-9f2a-d1969db7ec91.png)

BeebEm also has (similar but different) issues:
![beebem](https://cloud.githubusercontent.com/assets/961548/13381295/7742fff8-de50-11e5-9c02-628e7911be93.png)

I'm guessing it is doing something a bit odd / clever which happens to work on a real BBC... Unfortunately I don't have one here to test.

Probably more useful non-embedded URL:
http://bbc.godbolt.org/?disc=https:8bs.nerdoftheherd.com/discimgs/8BS12.dsd&loadBasic=https://8bs.nerdoftheherd.com/8BS12/content/0-b-devils/emulate.bas&autorun

**Comment by mattgodbolt** [comment]
Thanks for the bug report! I'll try and dig into this during the week!

**Comment by mattgodbolt** [comment]
Interestingly I loaded it through the normal menu and - apart from a bit of jitter - it seems to work fine. Seems like it's a dodgy timing interrupt doing a mode switch. The mode switch happens ok but seemingly at a somewhat random line give or take 3-or-so lines!

![image](https://cloud.githubusercontent.com/assets/633973/13385151/2a9b7b72-de63-11e5-8649-d755bac7ed5f.png)

With issues like this before it has been the setup code for these things being flakey. jsbeeb - especially with autoboot - presents an identical setup each time (timings and all) which means if there's a timing bug it'll happen every time if it happens at all.

I'll dig more to try and prove this out though!

**Comment by mattgodbolt** [comment]
Cursory examination:
60e5 -> irq routine
6165 -> vblank; programs timer 2 to 2a60
617a -> t2 irq; alternates between two routines 61cc and 6183
61cc -> pokes video R1=0x28 R8=0x08
6183 -> pokes video R8=0x31 R1=0x00 R2=0x31 and sets palette

in general the IRQ handler seems pretty naive: checking both FE4D and FE4E ... twice. The palette setting seems pretty long-winded too. Might explains the jitter...but that said; I can't see quite why it'd be wrong some times and not others.

**Comment by richtw1** [comment]
Sounds more like an uninitialized state bug to me (in the Beeb code!).  That said, the results when running it on a Master are totally peculiar!

**Comment by ribbons** [comment]
B-em gives me a similar result to when you ran it in JSBeeb from the menu:
![b-em](https://cloud.githubusercontent.com/assets/961548/13407569/ee05b4ac-df20-11e5-85d5-cfdebf0392d4.png)

I've tried running it from the menu a good few more times and it seems to mostly give me the same result as running it directly, but sometimes it gives very odd output!

![jsbeeb_menu](https://cloud.githubusercontent.com/assets/961548/13407743/f01e00d6-df21-11e5-8d98-52697a4b0f38.png)

Not sure if I'm helping here or just adding to the general noise...

**Comment by mattgodbolt** [comment]
I just realised the DSD support was completely broken...so this probably needs a re-check...

**Comment by ribbons** [comment]
> I just realised the DSD support was completely broken...so this probably needs a re-check...

Behaviour seems similar to before... Except that I can't seem to get the text to display even if I load it manually via the menu.  Might just be random luck on my part though!

Seems less messed up in Master 128 mode too so I think this shows how JSBeeb is improving :smile:

**Comment by scarybeasts** [comment]
Oh very interesting. Latest deal is that text is displaying reliably but is wobbling up and down. b2 can display this steadily.
I wonder where that jitter is coming from in jsbeeb (b-em seems identical) -- I bet this one is very interesting, I will aim to take a look.

**Comment by ribbons** [comment]
Funnily enough I was going to flag this up to you yesterday @scarybeasts (but forgot) as I thought you might find it interesting - I think the text displaying at all is due to your recent timing fixes 🙂.

**Comment by scarybeasts** [comment]
@mattgodbolt @richtw1 I think I have a simple fix for the immediate issue. One of these things where it's tricky to diagnose but not too tricky to fix. I'll paste my notes on the full story shortly.

On a more general question, who should I ask for questions on the CRTC code? I'm curious why this.handleHsync() does horizontal flyback half-way through the hsync pulse. Other emulators tend to do it at the start.

I'd also love any links on the half-clock horizontal movement trick. I can't understand how a real CRT device would respond in that way just because the hsync pulse is for an odd number of clocks??

**Comment by richtw1** [comment]
I can assist with crtc stuff! The flyback in the middle of the pulse is the
hack that lets the R3 trick work. No one really understands why or if it
makes sense to model it like that - one possible explanation is that the
CRT reacts to either the start or end of the pulse, but also has its own
natural frequency which it wants to oscillate at, and the result of the
fight is that the phase ends up getting pushed to the middle of the pulse.
Something about phase locked loops... Which can also model the more
realistic behaviour of the horizontal border moving gradually, not
instantly, on an hsync change.

**Comment by scarybeasts** [comment]
Thanks @richtw1 

In terms of the issue tracked by this bug, here is what is going on. The interrupt handling setup is kind of imprecise and as a consequence, racy.

- The vsync IRQ triggers with some timing jitter, because of the normal 2 - 7 cycle 6502 instruction variation, and also because the program is spinning inside MOS (OSRDCH?) which has a little SEI block as part of the loop.
- vsync IRQ sets up a new timer, based on a static value, so no jitter is smoothed out.
- Timer IRQ triggers about half-way down the frame, adding to the jitter for the same reasons the vsync IRQ is jittery.
- In this timer IRQ handler, the video output is disabled. This accounts for the jumpy green line: depending on jitter. video output is turned off at different CRTC horizontal counter positions. The jumpy green line does not represent any emulation bugs.
- Also in the timer IRQ handler, the horizontal position CRTC register is rewritten from $2E to $31.
- Here is the race. Occasionally, the jitter lines up such that the CRTC horizontal counter is ~$2E when the horizontal position register is rewritten. This will lead to hsync triggering twice for one scanline: at $2E and $31.
- The race triggers a corner case jsbeeb CRTC bug. If hsync is triggered while the hsync pulse is still ongoing, jsbeeb will still incorrectly bump the simulated CRT beam down twice when it should be once.

It's a trivial patch, we can match b2 behavior for now. Patch incoming,

**Comment by ribbons** [comment]
Thanks for your hard work on this one @scarybeasts - just tried it on a checked-out copy of your PR and the jitter is no-more :+1. Don't think I'd have figured that out in a month of Sundays!

According to the details in the issue (https://8bs.nerdoftheherd.com/8BS12/content/2-devlife/) the game was created with 'INCENTIVES Graphical Adventure Creator'.  I wonder if all of the adventures created with that software for the beeb are as buggy?
