### ISSUE TITLE
CRTC fidelity - widescreen modes

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#119]
Try this:
MODE 3
VDU 19,0,4,0,0,0
*HELP
VDU 23;9,7;0;0;0
VDU 19,0,1,0,0,0
When we collapse the venetian blinds, we get some stray graphics at the bottom of the screen, which don't change colour with the main part. I'm not sure if the stuff at the bottom should be there, but if it should, I think it should change colour. (I have not tested on real hardware.)

See http://stardot.org.uk/forums/viewtopic.php?p=144143#p144143

**Comment by mattgodbolt** [comment]
Thanks Ed. @richtw1 any thoughts?

**Comment by scarybeasts** [comment]
Hmm, this one seems pretty easy to diagnose just looking at the code. In the "collapsed MODE 3", the vsync is triggered much higher on the simulated CRTC display, and the drawing code simply doesn't draw to the canvas in the affected locations.

I suspect a real CRTC wouldn't sync to this resulting mode because it'll be significantly >50Hz but you never know.

I suppose if we wanted to be both fast and accurate, we could blank out any lower canvas lines for the case where the CRTC flyback canvas line has decreased.

I also suppose you could construct a test case that has the same "staleness" but for an early hsync, leading to stripe to the right of the display.
