### ISSUE TITLE
Periodic noise out of tune

### ISSUE THREAD

**Issue by richtw-epic** [mattgodbolt/jsbeeb#124]
Kieran's VGM tracker demo is horribly out of tune, also see Icarus for an example.

**Comment by kieranhj** [comment]
Depends on the tune - some of them were impossible to completely retune to BBC SN frequency as the notes are out of range.  Also, anything that relies on the high / medium / low periodic noise will sound wrong.  Check with @simondotm for details of his vgm conversion script.

**Comment by richtw1** [comment]
Should work the same as real hardware now, at least. With the changes in master branch, your demos sound lovely again! And Icarus also sounds correct now.

(But yeah, converting VGMs from platforms with different versions of the SN76489 will need the periodic noise pitches adjusting by 15/16 so that they remain in tune... or adjusting the pure tone pitches by 16/15 if high/medium/low periodic noise is used, provided you don't end up exceeding pitch 1024...)

**Comment by kieranhj** [comment]
Yay, thanks Rich!  Yes, Simon worked out all the maths to correctly adjust all the tunes from other SN specs.  The periodic noise pitch being the biggest PITA I understand.

**Comment by mattgodbolt** [comment]
Thanks!

The beta site hasn't updated as I run the git hook from home and my home
internet is out; in case you wondered!

**Comment by simondotm** [comment]
Great stuff, thanks Rich. I'll sync our repo with the latest version.
As Kieran mentioned, I spent a while looking specifically at periodic noise since it's pretty fiddly to transpose given it's tied to the frequency on another channel. My script is [here](https://github.com/simondotm/vgm-converter) if its of interest to anyone in future.

**Comment by richtw1** [comment]
In case it helps you scrape a bit more frequency range out of the chip, I saw in recalc_frequency that you clamp to 1023, when in fact you can clamp to 1024 (but write 0 in this special case).  Might not make a lot of difference but the Beeb is terrible at bassy pure tones, so it might help a little.  (In my music player for Blurp, I synthesize more bassy tones using freq=1 and a timer to modulate it with an interrupt!)

**Comment by mattgodbolt** [comment]
I've manually updated the beta site for now. Thanks for fixing this Rich!

**Comment by simondotm** [comment]
Time to get my head around github submodules i think! 
Might be worth dropping the bbcmicro.co.uk team of this fix as they too have their own instance of jsbeeb and it'll probably fix some in game music nicely.

**Comment by simondotm** [comment]
I will look at the tweak you mentioned also Rich, thanks for the tip.

**Comment by mattgodbolt** [comment]
Right: I was wondering how you might be doing the integration. submodules
are probably the right thing...they're a little confusing but should do the
job right.
