### ISSUE TITLE
Uridium compatibility issue

### ISSUE THREAD

**Issue by richard-broadhurst** [mattgodbolt/jsbeeb#130]
http://stardot.org.uk/forums/viewtopic.php?f=51&t=11165&start=210#p150166

I wonder if it is another bug in the original game, being triggered by a timing issue being aggravated by the syncing of the keyboard interrupt with vsync in jsbeeb (if that is even still the case).

**Comment by murkle** [comment]
Here's some info about how Uridium's screen handling works from the author of PCBBC

Knowing which games gave PCBBC a problem might help.



1) Psycastria - had problem with timers (your's dosen't however in the

original the play area was centred on the screen...)

2) Firetrack - good attempt- but the scrolling is very jerky + original

mode & bit does not fir on screen.

3) Uridium - Uses a negative screen position offset so that there are in effect

2 screens on the display at the same time. The first is not hardware

scrolled and the second is - hence title is above scrolling play area.

Beebit seems not to cope with this.

4) Revs - Register and interrupt timings. Most

games wait for vsynch and set interrups on this. revs gets one then sets

another for later then another for later - so the timings have to be

exact.

5) Skirmish - Register timings to prevent scrolling "lava"


>but I am still having problems with Revs and a few others. 

Yes.  Revs is a pain because it doesn't use the 50Hz IRQ from the 6845

on each frame!  Instead it tests this once, at the start of each game

(as it swaps from Mode 7 to graphics mode) and then relies on the fact

that the 6845 is perfectly locked to the video refresh rate.  This is a

real pain for your video emulation.  Also, note that if you get it right

for Revs then Psycastria, which uses the same trick, probably WON'T

work!  I'll leave you to find out why! ;-)


>I have heard

>that there should be a delay between the IRQ being set and the vector being

>called but cannot find any information about this. 

Really it's all down to the fact that the 6502 CPU clock is slowed to

1MHz when accessing the 6522.  However this is unimportant for Revs

since it always sets the latches and these get transferred automatically

at timeout by the CPU.  Look at the OS.  It writes &270E into the system

T2 timer, which is 9998 decimal for an exact 100Hz interrupt.  Strange!

This tells us that the 6522 timers interrupt as they cross 0000 to FFFF

(not when they reach 0) and also that it takes the 6522 one (1Mhz) clock

cycle to move the latches into the counter.  Therefore the value loaded

into the latches has to be 2 less than the actual number of 6522 clocks

between IRQ's.

I'd say the problem lies with your 6845 timing not being locked to the

system clock and possibly your 6522 interrupts being one 1MHz cycle out.  



The only time you need to worry about the extra cycles it takes to

access the 1MHz 6522 is when you come across a game (Bone Cruncher for

example) which uses values read from the 6522 timer to EOR decrypt

itself.  Nasty!



>Would you be able to

>clarify exactly how this all works or let me know where I can find out?

To the best of my knowledge there is nowhere to find this out.  There

might be a little detail in the 6522 data sheets, I don't know for sure

as I've not looked.  The best way is to write some test software on the

Beeb and see if your Em performs the same.  Then of course, when you

release, you can wait for people to send you games which don't work!



>Likewise with the screen scanline timing. When can I get info on how this

>works?

Again, experimentation.  It's fairly logical really.  There are 625.5

lines on an interlaced display.  On a non interlaced display there are

625 lines.  Each line consists of R0+1 characters.  The clock of the

6845 is locked to either a 2MHz or 1MHz signal (depending on the clock

rate set in the Video ULA for fast/slow modes) so that reads of the RAM

by the 6845 are interleaved with the CPU.  An HSYNC therefore occurs

after R0+1 CPU clocks in fast modes and R0*2+1 clocks in slow modes.  A

screen consists of R4+1 character rows, each of R9+1 lines plus an

adjustment of R5 lines at the bottom.  This is as per the diagram on

page 360 of the AUG, which always seemed a bit weird (the screen is

shown in the top left hand corner of the display), until you realise

that R7 and R2 haven't been shown.



   <----------R1------------>

   <-------------R2---------------->

   <-----------------R0+1----------------->

^^^+------------------------+------+------+

||||                        |      |      |

||||                        |      H      |

||||                        |      S      |

RRR|      Display           |      Y      |

674|       Area             |      N      |

||+|                        |      C      |

||1|                        |      |      |

v||+------------------------+------+------+

 |||                        |      |      |

 v|+----VSYNC---------------+------+------+

  ||                        |      |      |

  v+------------------------+------+------+



Note that the VSYNC occurs when the internal line counter in the 6845

(which starts life at a value of R4) reaches the value in R7 and then

the display area begins when it crosses 0.  The display period lasts for

R6 character rows.



Note that you can change all these values on the fly to create multiple

display areas on the same screen!  Also note that most of the other

registers can be changed on the fly too, which is how FireTrack does it

smooth vertical scroll.



>I think I've got it correct, but since every emulator writer has done it

>differently, it's very hard to get exact clarifiaction of the timing.

The only way I got it right was through trying as many games as

possible!  For an extensive workout of your emulated 6845 try:

Boffin          (increases width of screen)

Revs            (free running interrupts)

Psycastria      (free running interrupts)

FireTrack       (smooth vertical scroll)

Uridium         (multiple display areas)

GAC Graphical Adventure (changes screen width on fly)



Hope I've been some help!


>After tracing the CRTC registers I can see what you mean. It's obviously

>changing the Vertical Sync and Display Enable to do this. Display Enable is

>the one area I have not figured out how to emulate yet. Do you have any

>info you can send to me on this?

I've been looking at the 6845 data sheets from the BBC doc project.

They confirm what I have discovered by experiment:



The 6845 consists of:

* The 18 registers, R0-R17

* 4 internal counters:

        HCC - Horizontal character counter (8 bits)

        HSS - Horizontal sync width counter (4 bits)

        CRC - Vertical character row counter (7 bits)

        SLC - Vertical scan line counter (5 bits)

* Numerous register/counter comparators

* Various control logic blocks



Basically the comparators compare the values in the registers with those

in the counters.  When they are equal this produces a control signal,

which has various effects such as resetting the counters or enabling or

disabling the display output.

        HCC is compared with R0, R1 and R2

        HSS is compared with R3

        CRC is compared with R4, R6, R7

        SLC is compared with R9



Basically HSS is irrelevant (as far as an emulator is concerned).  So,

starting with HCC, CRC and SLC at 0:



When HCC=R1 The horizontal display field ends (start of H blanking)

When HCC=R2 A H-sync event occurs

When HCC=R0 HCC is reset to 0, the horizontal display field starts (end

of H blanking) and SLC increments



When SLC=R9 SLC is reset to 0 and CRC increments



When CRC=R5 The vertical display field ends (start of V blanking)

When CRC=R7 A V-sync event occurs, also the Vertical Control logic

inserts an extra half a scan line if interlace is enabled and uses the

value in R5 to display any extra "odd" lines required

When CRC=R6 CRC is reset to 0, the vertical display field starts (end of

V blanking)



Hope that makes sense!



Under "normal" conditions R5<R7<R6, which makes a valid display.

However, if R7>R6 it can be seen that no V-sync will ever be produced!

Normally, this would be disastrous, however we can use it to our

advantage!  If we program interrupts to change these values on the fly,

we can make CRC cycle from 0 to R6 twice within a single frame while

only generating 1 v-sync.  Hence we get 2 vertical display areas per

frame.  Uridium does exactly this, and is able to hold one of the

display areas still while horizontally scrolling the other.



>>>>Uridium         (multiple display areas)

>This one took me a whole week to work out.  It's really very ingenious,

>in some ways even more cleaver than FireTrack.



After tracing the CRTC registers I can see what you mean. It's obviously changing the Vertical Sync and Display Enable to do this. Display Enable is the one area I have not figured out how to emulate yet. Do you have any info you can send to me on this?



Dump from CRTC r0-r9 (number in brackets is value written)

127 64 90 40 18 4 16 32 (240) 7 

127 64 90 40 18 4 16 (3) 240 7 

127 64 90 40 18 4 16 3 (192) 7 

127 64 90 40 18 4 16 (32) 192 7 

127 64 90 40 18 4 16 32 (192) 7 



>Do I need to generate a horizontal sync pulse at all? If so, what needs to

>happen?

H-sync is invisible as far as the 6502 is concerned.  However I assume

your Em must know about it in order to get the video timing correct.

pcBBC assumes that H-sync always occurs at the correct frequency (TV's

and monitors for the BBC expect a fixed h-sync and v-sync frequency).

Therefore no BBC software (at least if it is functioning correctly!) is

ever going to change this.



pcBBC assumes that h-sync occurs every 128 processor clocks (2Mhz), but

you could derive this value from R0.  You must also add 1/2 the value in

R0 on each frame if interlace is enabled, and remember to double R0 if

the video ULA is programmed for a slow clock rate mode (Modes 4-7).

**Comment by scarybeasts** [comment]
Here is what is going on with Uridium.

This applies to the STH version and the bbcmicro.co.uk version. The latter makes a better attempt to avoid the problem, but still does not avoid the problem.

The crux is that execution of the game loader arrives at &6F00, with _IRQs enabled_. It proceeds to set up and execute a copy from &1100 to &200. Furthermore, the ensuing write to IRQV points to &200.
There are various problems and race conditions here but the one most likely to trigger is where &0204 (IRQV) has been overwritten with &0200, but then an IRQ occurs shortly after, and before the full IRQ handler code at &0200 has been written.

Attached a patched Uridium (based on bbcmicro.co.uk) that just moves an SEI and should work better.

There remains a race &2532 where EVENTV is set with IRQs enabled which is a problem if a vsync triggers when one byte of EVENTV has been written but not the other. This is a very small race window though so is not addressed in the fixed version.

[uridium_fixed.zip](https://github.com/mattgodbolt/jsbeeb/files/3463419/uridium_fixed.zip)

There's still a separate problem with the keyboard not working in Master mode in b-em / jsbeeb, but that's an emulator bug. For now, use normal BBC B mode.

I don't think there's a jsbeeb change to make here; perhaps we can close?

**Comment by scarybeasts** [comment]
@richard-broadhurst let @mattgodbolt and I know if this is a satisfactory explanation and fixed version of Uridium, would be great to close this.

**Comment by scarybeasts** [comment]
Ah, ignore my fixed version, there's already a decent working version here: https://stardot.org.uk/forums/viewtopic.php?f=51&t=13967&p=184720#p184671

**Comment by richtw1** [comment]
Does the tape version (from STH, directly accessible from bbc.godbolt.org) contain this code as well? The tape images are completely unmodified and should serve as our best guide to the original versions. If this is working ok, I would heavily suspect that the disk image is a clumsy hack job from someone else.

**Comment by scarybeasts** [comment]
@richtw1 The tape version appears to have a version of the loop at &4ABE, which is writing to &0200 but correctly runs with interrupts disabled. Interestingly, the tape version is pulling the source bytes from (I think...) the tape serial registers directly. So yeah it would need to be a hack job if the disc ssd's are based on the tape version.

Bill Carr's version linked above was transferred to disk correctly as far as I can tell, with interrupts disabled for the critical loop.

**Comment by scarybeasts** [comment]
@mattgodbolt Please close -- one of the bbcmicro.co.uk admins did a bit of checking and the non-buggy Uridium disc is fine in BBC B mode.

There's still the other bug regarding Uridium keyboard failure in master mode which I'm working on.
