### ISSUE TITLE
Help text isn't up to date

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#161]
The text in the Help pane in JSBeeb still says that the colon/asterisk key-mapping is "TODO" for both PC and "OSX". Is that accurate? I'm on a Mac and I'm not having any problems: the Beeb's colon/asterisk key is mapped to the physical apostrophe/quotation-mark key on my Mac, which is exactly what I would expect. I think the same is true on a PC too.

**Comment by BigEd** [comment]
(I'm on a Mac too, and colon/asterisk also works for me. For clarity, mine is a MacBook Air, with a UK keyboard. That is, normally shift-2 is @, alt-2 is €, shift-3 is £ and alt-3 is #. In jsbeeb, shift-2 is " and shift-3 is #, as expected.  Stardot user sa_scott has a 2014 iMac wireless keyboard, possibly a US model, and reports having difficulty:
http://stardot.org.uk/forums/viewtopic.php?p=188941#p188941

I am generally using the 'Physical' mapping in the Keyboard menu, which is I think the mapping described in the Help popup. It would be useful to mention the two mappings in the Help popup, and to say that it's the Physical mapping being described. For me the 'Natural' mapping works poorly, for example shift-6 should be ^ but in jsbeeb gives &.)

**Comment by sassquad** [comment]
Apologies for coming late to this. Yes, I did raise this on Stardot.

I'm using a 2014 iMac (purchased in the UK), which is installed with Mac OS High Sierra. This uses Apple's Wireless Bluetooth keyboard, where the ' key would normally work. For some reason, I cannot get this to work on JSBeeb, no matter which Keyboard option I pick from the menu.

The keyboard is set to UK. I've tried changing it to US keyboard layout, and I get no joy, except for the option which involves using the keyboard combination of Shift + 8. I'm no contortionist, and cannot play games like this :-(

I had another go late last night, and was again unsuccessful in getting anything to work. The fact that other Mac users can play without incident is all the more annoying.

I've been using Chrome all this time. I do have Safari and Firefox however. I've tried to install the Mac version of Beebem, but it quits in attempting to run, which may be due to the OS.

If there's anything I can do to help in addressing this issue, I would be extremely grateful.

**Comment by ahope1** [comment]
@sassquad Check the Stardot thread!

**Comment by sassquad** [comment]
Thanks @ahope1 - I've responded there. I have a 2013 iMac at work, with a similar setup. I'll try jsBeeb there, and use another browser as well, to see if it's unique to my machine (or not).

**Comment by murkle** [comment]
What keycode does the problem key give here?
http://jsfiddle.net/Sk8erPeter/EAjYe/6/

**Comment by sassquad** [comment]
@murkle The problem key emits 222.

Having tried on Chrome on the office iMac, I got the same problem, the same key won't work.

However, on Firefox 57, the key **does** work, whichever keyboard layout I select, it works.

Therefore, Chrome has been taking the mickey!

Wonder what's at issue here, the way Chrome is interpreting keydown events compared to Firefox?

**Comment by murkle** [comment]
What keycode does it give in Firefox?

**Comment by sassquad** [comment]
@murkle Firefox 57 also reports 222 for the ' key on the iMac.

Interestingly the ; key next to the ' key reports different values. In Chrome it reports 186, while Firefox reports 59.

**Comment by ahope1** [comment]
For what it's worth, I'm also on a Mac, and I _can_ use JSBeeb in Chrime without any problems.

**Comment by BigEd** [comment]
On my Mac, the laptop keyboard works fine but I have a USB keyboard which doesn't.

**Comment by mattgodbolt** [comment]
Keyboard woes are a right nightmare. Looks like there's now a way to detect the right layout(s) - that's captured in #321 , so I'm going to close this off
