### ISSUE TITLE
Disc drive seems to erroneously reset to track 0

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#165]
Lots of seeks to and from track zero that don't seem to happen in b-em etc

**Comment by mattgodbolt** [comment]
Also see kieranhj/pop-beeb#55 for some timings to compare with

**Comment by scarybeasts** [comment]
Looking -- the bbcmicro.co.uk admins were asking me about slow load times.

To briefly quantify, the Enjoy The Silence disk is a great example. How many large seeks prior to title screen?
- Currently hosted jsbeeb: 7
- My hacked up / fixed(?) build: 1

**Comment by scarybeasts** [comment]
Root cause here is a workaround for Elite-A leading to unusual controller behavior. This is partly conjecture, but it looks like returning "drive not ready" all the time causes DFS to assume the disc could have been changed and toss its directory entry cache or something like that?

The Elite-A issue is interesting. It looks like it could rely on some form of invalidation occurring in order to fix some cache corruption. In the failure case, it's just a couple of OSCLI calls:
*R.1.F
*L.S.K
The *LOAD fails even though the file is there.
The first file loads at &1153 which is right inside the DFS work space.

E00-DFS, loaded as a sideways RAM, seems to fix the failure.

Anyway, I've got a patch that seems to balance all of this and still have Elite-A work.
