### ISSUE TITLE
Speech samples don't play correctly

### ISSUE THREAD

**Issue by lurkio** [mattgodbolt/jsbeeb#167]
The following speech sample programs just produce audio noise:

http://bbcmicro.co.uk//jsbeeb/play.php?autoboot&disc=http://bbcmicro.co.uk/gameimg/discs/1411/ReetPetite.ssd

http://bbcmicro.co.uk//jsbeeb/play.php?disc=http://bbcmicro.co.uk/gameimg/discs/1411/Speech.dsd&patch=@bc09,3e0:2a5350454543480d;@bc09,2d8:e0;@bc09,2e1:e8

More info on Stardot:

http://stardot.org.uk/forums/viewtopic.php?f=2&t=14653&p=196778#p196073

**Comment by mattgodbolt** [comment]
Ooh crikey, that's no good :) thanks!

**Comment by lurkio** [comment]
@mattgodbolt This one doesn't work either:

https://bitshifters.github.io/posts/archives/tyb-enjoy.html

**Comment by mattgodbolt** [comment]
Thanks! And one of my favourite songs too! I'll have to fix it :-)

**Comment by scarybeasts** [comment]
The PR fixes ReetPetite.ssd and tyb-enjoy.ssd but Speech.dsd is a different issue and I'll file a new issue once this one is closed.

**Comment by mattgodbolt** [comment]
Confirmed Reet Petite works on bbc.godbolt.org (though #165 or similar makes the whole thing a noisy discfest). I couldn't get speech to work on bbc.godbolt.org (maybe due to the patch thing that I see is in the URL)

Joyously. https://bbc.godbolt.org/?disc=https://bitshifters.github.io/content/tyb-enjoy.ssd&autoboot&model=Master now works! (and is pretty amazing!)

**Comment by lurkio** [comment]
> I couldn't get speech to work on bbc.godbolt.org (maybe due to the patch thing that I see is in the URL)

The patch just inserts *SPEECH into the keyboard buffer.

**Comment by lurkio** [comment]
> Reet Petite works on bbc.godbolt.org (though #165 or similar makes the whole thing a noisy discfest)

Yes, it really would be great if there was a URL param to switch disc-drive noises off.

**Comment by scarybeasts** [comment]
Just to confirm, Speech.dsd was not expected to be fully fixed by this patched.
Speech.dsd does set the period to 8 for sample playback (an unusually large value) and that should also be catered for by this patch.
However, Speech.dsd _also_ does the weird thing of turning on write enable to the sound chip without ever turning it off. Current emulators don't handle that but now we have evidence that a real beeb is happy with the arrangement. I'll file and fix under the umbrella of a different bug.
