### ISSUE TITLE
Star Drifter tape version fails in custom tape loader

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#257]
https://bbc.godbolt.org/?&tape=sth%3AFirebird%2FStarDrifter_B.hq.zip#

Don't know if related to the other issue with the UEF state machine.

**Comment by scarybeasts** [comment]
Hmm, I did see one other place in UEF that might be capable of triggered a similar error, maybe this hits it? I'll have a look as soon as time permits.

**Comment by scarybeasts** [comment]
This one may be something different. It's interesting, initial notes:

- b-em can't load the custom blocks at all, it fails with Data? on the first one.
- jsbeeb handles about 6 or so before bailing with Block?
- beebem can actually load the entire game!

As jsbeeb fails, there's a lot of "serial overrun" in the console.

**Comment by scarybeasts** [comment]
Also ran through this list, as well as Atic Atac, The Hacker and Chip Buster, to make sure we're doing ok: http://beebwiki.mdfs.net/List_of_copy_protected_software_titles_on_cassette

**Comment by scarybeasts** [comment]
(Looks like Caveman Capers could have an issue, I'll investigate in a separate bug if necessary.)

**Comment by scarybeasts** [comment]
- Custom loader hits &FE08 and &FE09 directly.
- While custom loader is running, interrupts are on and MOS is ticking its timer -- presumably for the sound player?
- Bit of timing variance, but eventually MOS timer tick occurs during an intra-block tone.
- Our current code holds DCD high while in an intra-tone block.
- MOS believes RS423 owns the serial, and it sees DCD high, so it reads the serial byte.
- Oh no! This steals the data byte from the custom loader.

The tape layout for the custom loader section has very short intra-block carrier tones. Turns out these are too short to trigger DCD high on real hardware.
