### ISSUE TITLE
Keys for Asteroids Deluxe don't work

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#29]
[from the author! yay] : "The only trouble is the keys don't quite work properly: 

  Ctrl turns right 
  Caps Lock turns left continuously when enabled but I think holding Shift should turn left - I can't quite remember. 
  ]  is thrust but I'm not sure that's right

...I've only tried it in Safari and Chrome on a MacBook with UK keyboard layout though. Elite and Defender seem to work OK.."

**Comment by jlarcombe** [comment]
For what it's worth, I noticed yesterday that the same thing happens in Zalaga running in Chrome on the Mac, and presumably any other game that uses caps lock to move left. Haven't debugged it, but it's as though jsbeeb 'sees' the key being held down continuously while the system's real caps lock is enabled.

**Comment by mattgodbolt** [comment]
Ah that could well be it! Thanks for the hint; though I'm not quite sure how one might go about fixing it. 

My caps lock key is configured as a completely different key so I've not seen the problem :)

**Comment by jlarcombe** [comment]
Looking around, it seems as though this would be impossible to fix without a change to the browsers. Cocoa simply doesn't issue key up events for caps lock. They'd have to go down to a lower layer (IOHIDManager) and that would be a pain because it wouldn't come through the normal event loop. The Qt and Firefox developers have had the same problem (https://bugzilla.mozilla.org/show_bug.cgi?id=712535, https://bugreports.qt.io/browse/QTBUG-46549).

The 'Gaming' keyboard layout works around the problem in jsbeeb, of course.

**Comment by murkle** [comment]
Another solution :)
http://bbc.godbolt.org/?autoboot&disc=sth%3AAardvark%2FZalaga.zip&KEY.A=CAPSLOCK&KEY.S=CTRL&keyLayout=physical#

**Comment by mattgodbolt** [comment]
Now jsbeeb will pop up a warning on Mac OS X. It seems intractable (have asked pals at Apple for help but don't expect much). Closing as "not planned" as I can't fix it generally.
