### ISSUE TITLE
CORS error when trying to load disk image from github

### ISSUE THREAD

**Issue by LoveBug2084** [mattgodbolt/jsbeeb#430]
I get a CORS error with jsbeeb running on my site when trying to load my LadyBug project disk image from github

https://lovebyte.eu.org/jsbeeb-main/?autoboot&noseek&disc=https://github.com/LoveBug2084/LadyBug/raw/main/src/Lady%20Bug.ssd

This use to work fine but now causes an error with the latest LibreWolf (firefox) browser update

Is this an actual issue or is it just me not knowing what im doing :rofl:

**Comment by mattgodbolt** [comment]
It's not in general possible to grab things from the github.com domain _by design_ - like github on purposes prevents CORS to stop e.g. jsbeeb reading content _as you_ because youre logged into gitbhu.

However the "raw" link of github (on githubusercontent or whatever) should work - 

https://lovebyte.eu.org/jsbeeb-main/?autoboot&noseek&disc=https://raw.githubusercontent.com/LoveBug2084/LadyBug/raw/main/src/Lady%20Bug.ssd 

should work

**Comment by mattgodbolt** [comment]
your jsbeeb seems down right now but here it is working ok on the main site: https://bbc.xania.org/?disc=https://raw.githubusercontent.com/LoveBug2084/LadyBug/main/src/Lady%20Bug.ssd

**Comment by mattgodbolt** [comment]
please reopen if you have any problems :)

**Comment by LoveBug2084** [comment]
oh it was a user error then sorry
what threw me was that it used to work until I updated my browser

thanks for your help

**Comment by mattgodbolt** [comment]
No problem at all! I wonder if the prior browser wasn't "doing it properly" as there's nothing jsbeeb can do to control what the browser or github does :)

The disc image looks very cool btw!

**Comment by LoveBug2084** [comment]
thanks, its a fun game but not as cool as your emulator

amazing work :star::star::star::star::star:
